---
title: "ETC513 Assignment 3: Comparison of Energy and Pollution by Country"
author:
- familyname: Chen
  othernames: Shaohu
  address: Monash Universtidy
  email: sche0232@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Business Analytics(In Progress)
- familyname: Duan
  othernames: Qian
  address: Monash Universtidy
  email: qdua0005@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Business Analytics(In Progress)
- familyname: Tsou
  othernames: Tina
  address: Monash Universtidy
  email: ttso0004@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Business Analytics(In Progress)
department: Our consultancy \newline add names &\newline add names
organization: Australian Government 
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE,echo = FALSE, message = FALSE, warning = FALSE,fig.align='center'}
# Libraries
library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
library(ggplot2)
library(plotly)
drive <- read_csv("Data/practicaldrivingexaminationresults.csv")
```

\section*{Introduction}




\section*{Step 1}
```{r,echo = FALSE, message = FALSE}
year_drive <- drive %>% 
 separate(col = Month, into = c("Year","Month"),"-") %>% 
  select(Year,`Local Government Authority`)  
num_year_drive <- year_drive %>% count(Year)

num_year_drive_percentage <- drive %>% 
  separate(col = Month, into = c("Year","Month"),"-") %>% 
  select(Year,Month,`Local Government Authority`,`Exam Result`) %>% 
  count(Year,`Exam Result`) %>% 
  arrange(desc(Year)) %>% 
  rename(num = n) %>% 
  right_join(num_year_drive) %>% 
  mutate(year_percentage = num/n) %>% 
  filter(`Exam Result` == 'PASS') %>% 
  rename(pass_num = num, total_num = n) %>% 
  select(Year,year_percentage)
```

```{r,echo = FALSE, message = FALSE}
num_drive <- year_drive %>% 
  count(Year,`Local Government Authority`) %>% 
  arrange(desc(Year)) 

percentage_num_drive <- drive %>% 
 separate(col = Month, into = c("Year","Month"),"-") %>% 
  select(Year,Month,`Local Government Authority`,`Exam Result`) %>% 
  count(Year,`Local Government Authority`,`Exam Result`) %>% 
  arrange(desc(Year)) %>% 
  rename(num = n) %>% 
  right_join(num_drive)  %>% 
  mutate(percentage = num/n)%>% 
  filter(`Exam Result` == 'PASS') %>% 
  rename(pass_num = num, total_num = n)%>% 
  left_join(num_year_drive_percentage)

num_dict <- percentage_num_drive %>% count(Year) %>% rename(total_num = n)
```

```{r Tab1, message = FALSE, warning= FALSE, echo=FALSE, fig.width= 15,fig.cap="The number of times the Local Government Authority obtains the highest or lowest pass rate per year"}
count_function <- function(x){percentage_num_drive %>% 
  select(Year,`Local Government Authority`,percentage) %>% 
  group_by(Year) %>% 
  filter(percentage == x(percentage)) %>% 
  group_by(`Local Government Authority`) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))}

max_percetage <- count_function(max) %>% head(6)
min_percetage <- count_function(min) %>% head(6)

knitr::kable(max_percetage,
             caption = "Number of time getteing the highest pass rate per year",
             booktabs = TRUE) %>%
   kable_styling(bootstrap_options  = c("striped", "hold_position")) 

knitr::kable(min_percetage,
             caption = "Number of time getteing the lowest pass rate per year",
             booktabs = TRUE) %>%
   kable_styling(bootstrap_options  = c("striped", "hold_position"))
```

In the table \@ref(tab:Tab1), BLACKALL-TAMBO REGIONAL COUNCIL has the most number of first (`r max_percetage$count[1]` times), MAREEBA SHIRE COUNCIL, NAPRANUM ABORIGINAL SHIRE COUNCIL, REDLAND CITY COUNCIL have won the last `r min_percetage$count[1]` times. 

\section*{Step 2}


\section*{Step 3}

